In [2]:
import pandas as pd
df = pd.read_excel("Stock.xlsx",index_col="Name")
df

                             Category  Price  Amount
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10
ปากกา                 อุปกรณ์การเรียน    200       5
โคมไฟ                เครื่องใช้ในบ้าน   1200       7
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0
เสื้อยืดคอกลม                เสื้อผ้า    500       2
กางเกงยีนต์                  เสื้อผ้า    999       8
ตุ๊กตาหมีพูห์                 ของเล่น    950       5
โซฟา                     เฟอร์นิเจอร์   5000       5
จาน                       เครื่องครัว    250       4
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7
ยางลบ                 อุปกรณ์การเรียน     20       5
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5
รถบังคับ                      ของเล่น    500       6

In [3]:
df["Delivery"] = 100
df

                             Category  Price  Amount  Delivery
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10       100
ปากกา                 อุปกรณ์การเรียน    200       5       100
โคมไฟ                เครื่องใช้ในบ้าน   1200       7       100
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1       100
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0       100
เสื้อยืดคอกลม                เสื้อผ้า    500       2       100
กางเกงยีนต์                  เสื้อผ้า    999       8       100
ตุ๊กตาหมีพูห์                 ของเล่น    950       5       100
โซฟา                     เฟอร์นิเจอร์   5000       5       100
จาน                       เครื่องครัว    250       4       100
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7       100
ยางลบ                 อุปกรณ์การเรียน     20       5       100
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7       100
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5       100
รถบังคับ                      ของเล่น    500       6       100

In [4]:
df["total"] = df["Price"] + df["Delivery"]
df

                             Category  Price  Amount  Delivery  total
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10       100   1000
ปากกา                 อุปกรณ์การเรียน    200       5       100    300
โคมไฟ                เครื่องใช้ในบ้าน   1200       7       100   1300
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1       100    850
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0       100   3600
เสื้อยืดคอกลม                เสื้อผ้า    500       2       100    600
กางเกงยีนต์                  เสื้อผ้า    999       8       100   1099
ตุ๊กตาหมีพูห์                 ของเล่น    950       5       100   1050
โซฟา                     เฟอร์นิเจอร์   5000       5       100   5100
จาน                       เครื่องครัว    250       4       100    350
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7       100  15100
ยางลบ                 อุปกรณ์การเรียน     20       5       100    120
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7       100   2600
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5       100    950
รถบังคับ                      ของเล่น    500       6       100    600

In [9]:
cols = {"Category":"Group"}
df.rename(columns=cols,inplace=True)
df

                                Group  Price  Amount  Delivery  total
Name
เมาส์              อุปกรณ์คอมพิวเตอร์    900      10       100   1000
ปากกา                 อุปกรณ์การเรียน    200       5       100    300
โคมไฟ                เครื่องใช้ในบ้าน   1200       7       100   1300
ไมโครโฟน              เครื่องใช้ไฟฟ้า    750       1       100    850
เครื่องซักผ้า         เครื่องใช้ไฟฟ้า   3500       0       100   3600
เสื้อยืดคอกลม                เสื้อผ้า    500       2       100    600
กางเกงยีนต์                  เสื้อผ้า    999       8       100   1099
ตุ๊กตาหมีพูห์                 ของเล่น    950       5       100   1050
โซฟา                     เฟอร์นิเจอร์   5000       5       100   5100
จาน                       เครื่องครัว    250       4       100    350
ทีวี                  เครื่องใช้ไฟฟ้า  15000       7       100  15100
ยางลบ                 อุปกรณ์การเรียน     20       5       100    120
External HardDisk  อุปกรณ์คอมพิวเตอร์   2500       7       100   2600
คีย์บอร์ด          อุปกรณ์คอมพิวเตอร์    850       5       100    950
รถบังคับ                      ของเล่น    500       6       100    600